# Generated by Django 5.0 on 2025-12-07 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserWeatherPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("favorite_city", models.CharField(max_length=100)),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "unit_preference",
                    models.CharField(
                        choices=[("celsius", "Celsius"), ("fahrenheit", "Fahrenheit")],
                        default="celsius",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("weather_watcher", "Weather Watcher"),
                            ("data_collector", "Data Collector"),
                            ("trend_analyst", "Trend Analyst"),
                            ("explorer", "Explorer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("points", models.IntegerField(default=10)),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("user_id", "achievement_type")},
            },
        ),
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("date", models.DateField(db_index=True)),
                ("temp_high", models.FloatField()),
                ("temp_low", models.FloatField()),
                ("temp_avg", models.FloatField(blank=True, null=True)),
                (
                    "precipitation",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "humidity",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("sunny", "Sunny"),
                            ("cloudy", "Cloudy"),
                            ("rainy", "Rainy"),
                            ("snowy", "Snowy"),
                            ("stormy", "Stormy"),
                            ("foggy", "Foggy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["city", "-date"], name="weather_wea_city_d5a988_idx"
                    ),
                    models.Index(fields=["-date"], name="weather_wea_date_d66bdb_idx"),
                ],
                "unique_together": {("city", "date")},
            },
        ),
    ]
