# Generated by Django 5.0 on 2025-12-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(db_index=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[("database", "Database"), ("api", "OpenWeather API")],
                        max_length=20,
                    ),
                ),
                ("searched_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("result_count", models.IntegerField(default=0)),
                ("found", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-searched_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "-searched_at"],
                        name="weather_sea_locatio_a312b9_idx",
                    ),
                    models.Index(
                        fields=["-searched_at"], name="weather_sea_searche_b2cd55_idx"
                    ),
                ],
            },
        ),
    ]
